config/routes.rb
KaljaaFb::Application.routes.draw do
	resources :accounts do
		member do
			get :following, :followers
		end
	end
	resources :sessions, only: [:new, :create, :destroy]
	resources :microposts, only: [:create, :destroy]
	resources :relationships, only: [:create, :destroy]
	resources :profiles do
		resources :albums
		member do
			get :info
		end
	end
	resources :activities
	resources :albums do
		resources :photos
	end
	resources :articles do
		resources :albums
	end
	resources :beers do
		resources :comments
		member { post :vote }
	end
	resources :beercentrals
	resources :blogs do
		resources :albums
	end
	resources :conversations, only: [:index, :show, :new, :create] do
		member do
			post :reply
			post :trash
			post :untrash
		end
	end
	resources :interests
	resources :invites do
		member do
			get 'admin'
			post 'admin'
		end
	end
	resources :events do
		resources :albums
		resources :blogs
		resources :articles
		member do
			get 'invite'
		end
	end
	resources :favbreweries
	resources :favbeers
	resources :friendships do
		member do
			post 'accept'
			get 'accept'
			post 'decline'
			get 'decline'
			post 'cancel'
			get 'cancel'
			post 'delete'
			get 'delete'
		end
	end
	resources :groups do
		resources :albums
		resources :blogs
		resources :articles
		member do
			get 'members'
		end
	end
	resources :honorablebeers
	resources :members do
		member do
			get 'admin'
			post 'admin'
		end
	end
	resources :messages
	resources :miscs
	resources :photos
	resources :abouts
	resources :locations
	resources :reviewbeers do
		resources :comments
		member { post :vote }
	end
	resources :services

	get "users/new"

	root to: 'home#index'

	match '/m_home', to: 'accounts#m_home'	
	match '/signup', to: 'accounts#new'
	match '/copyright', to: 'home#copyright'
	match '/faq', to: 'home#faq'
	match '/learn', to: 'home#learn'
	match '/privacy', to: 'home#privacy'
	match '/support', to: 'home#support'
	match '/terms', to: 'home#terms'
	match '/register', to: 'home#register'
	match '/signin', to: 'sessions#new'
	match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :content, :profile_id, :title, :word_on_the_street, :event_id, :group_id

	belongs_to :profile
	belongs_to :event
	belongs_to :group
	has_many :album

	validates :title, presence: true	
	validates :content, presence: true
	validates :profile_id, presence: true
	validates :word_on_the_street, presence: true

	default_scope order: 'articles.created_at DESC'

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_filter :signed_in_user
	before_filter :correct_user,   only: [:edit, :update, :destroy]
	#before_filter :admin_user,     only: [:edit, :update]
	respond_to :json, :html, :xml, :js

	def index
		@articles = Article.paginate(page: params[:page])
		#@profile_id= @articles.profile_id
		#@profile= Profile.find(@profile_id)
	end

	def show
		@article= Article.find(params[:id])
		@article_album = Album.find_by_article_id(@article)
		@profile_id= @article.profile_id
		@profile= Profile.find(@profile_id)
		@account_id= @profile.account_id
		@account = Account.find(@account_id)
		@album = @article.album.build

	end

	def create
		@profile= current_user.profile
		@article = @profile.article.build(params[:article])
		if @article.save
			flash[:success] = "Article created!"
			redirect_to @article
		else
			render new_article_path
		end
	end

	def edit
		@profile= current_profile
		@article = Article.find(params[:id])
	end

	def destroy
		@profile = current_profile
		@article = Article.find(params[:id])
		if @article.present?
			@article.destroy
		end
		respond_with @profile
	end

	def new
		@profile = current_profile
		@article = @profile.article.build
	end

	def update
		@article= Article.find(params[:id])
		if @article.update_attributes(params[:article])
			flash[:success] = "Beers updated"
			respond_with @article
		else
			render @article
		end
	end

	def info
	end

	private

	def correct_user

		#finds article then matches profile_id to Profile then matches matches account_id to Account then asks if its current user 
		@article_id= Article.find(params[:id])
		@profile_id = @article_id.profile_id
		@profile = Profile.find(@profile_id)
		@account_id= @profile.account_id
		@account = Account.find(@account_id)
		redirect_to(@profile) unless current_user?(@account)
	end

	def admin_user
		redirect_to(root_path) unless current_user.admin?
	end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<li>
	<%= link_to article.title, article %> <br>
	<%= article.profile.s1 %>
	Posted <%= time_ago_in_words(article.created_at) %> ago.
	<% if current_profile?(article.profile) %>
		<%= link_to 'Edit Article',  edit_article_path(article.id) %>
		<%= link_to "delete", article, method: :delete,
							 data: { confirm: "You sure?" },
							 title: article.content %>
	<% end %>

</li>

app/views/articles/_articles.html.erb
<% if @profile.article.any? %>
	<h3>News Started (<%= @profile.article.count %>)</h3>
	<ol class="beers">
		<%= render @articles %>
	</ol>
	<%= will_paginate @articles %>
<% end %>

app/views/articles/edit.html.erb
<%= link_to "Return to "+@article.title, @article %>

<%= form_for(@article) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">

		<%= f.label :title, 'News Title:' %>	
		<%= f.text_field :title, placeholder: "News title..." %>

		<%= f.label :content, 'Content:' %>		
		<%= f.text_area :content, :class => "tinymce", :rows => 40, :cols => 120 %>

	</div>
	<%= f.submit "Save changes"%>
	<%= link_to "Cancel", @profile %>
<% end %>

<%= tinymce %>

app/views/articles/index.html.erb
<%= link_to "Start News Article", new_article_path %>

<h1>News</h1>

<%= will_paginate %>

<ul class="list_3_12">
<% @articles.each do |article| %>
	<li>
	<%= link_to article.title, article %> <br>
	<%= article.profile.s1 %>
	Posted <%= time_ago_in_words(article.created_at) %> ago.

	</li>
<% end %>
</ul>

<%= will_paginate %>

app/views/articles/new.html.erb
<%= form_for(@article) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">

		<%= f.label :title, 'News Article Title:' %>	
		<%= f.text_field :title, placeholder: "News title..." %>

		<%= f.label :content, 'Content:' %>		
		<%= f.text_area :content, :class => "tinymce", :rows => 40, :cols => 120 %>

		<% if @profile.account.ty == "social" %>	

			<%= f.hidden_field :word_on_the_street, value: "1"  %>

		<% else %>

			<%= f.hidden_field :word_on_the_street, value: "0"  %>

		<% end %>

		<%= f.hidden_field :event_id, :value => params[:event_id]  %>

		<%= f.hidden_field :group_id, :value => params[:group_id]  %>
			
	</div>
	<%= f.submit "Post"%>
	<%= link_to "Cancel", @profile %>
<% end %>

<%= tinymce %>

app/views/articles/show.html.erb
<% if @article.event_id != nil %>
		<%= @article.event.title %>
<% end %>
<% if @article.group_id != nil %>
		<%= @article.group.title %>
<% end %>
<%= @article.title %>
<% if current_profile?(@article.profile) && !@article_album %>
	<%= form_for(@album) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		<div class="field">

			<%= f.hidden_field :title, :value => @article.title %>

			<%= f.hidden_field :description, :value => '' %>

			<%= f.hidden_field :article_id, :value => @article.id %>

		</div>
		<%= f.submit "Add Photos"%>
	<% end %>
<% else %>
	<%= link_to "Photos", [@article, @article_album] %>
<% end %>
<%= @article.content.html_safe %>
<% if current_profile?(@article.profile) %>
		<%= link_to 'Edit News article',  edit_article_path(@article.id) %>
		<%= link_to "delete", @article, method: :delete,
				                 data: { confirm: "You sure?" },
				                 title: @article.content %>
	<% end %>

<%= link_to "Return to News Central", articles_path %>
<% if @article.event_id != nil %>
		<%= link_to "Return to Event", event_path(@article.event_id) %>
<% end %>
<% if @article.group_id != nil %>
		<%= link_to "Return to Group", group_path(@article.group_id) %>
<% end %>