config/routes.rb
KaljaaFb::Application.routes.draw do
	resources :accounts do
		member do
			get :following, :followers
		end
	end
	resources :sessions, only: [:new, :create, :destroy]
	resources :microposts, only: [:create, :destroy]
	resources :relationships, only: [:create, :destroy]
	resources :profiles do
		resources :albums
		member do
			get :info
		end
	end
	resources :activities
	resources :albums do
		resources :photos
	end
	resources :articles do
		resources :albums
	end
	resources :beers do
		resources :comments
		member { post :vote }
	end
	resources :beercentrals
	resources :blogs do
		resources :albums
	end
	resources :conversations, only: [:index, :show, :new, :create] do
		member do
			post :reply
			post :trash
			post :untrash
		end
	end
	resources :interests
	resources :invites do
		member do
			get 'admin'
			post 'admin'
		end
	end
	resources :events do
		resources :albums
		resources :blogs
		resources :articles
		member do
			get 'invite'
		end
	end
	resources :favbreweries
	resources :favbeers
	resources :friendships do
		member do
			post 'accept'
			get 'accept'
			post 'decline'
			get 'decline'
			post 'cancel'
			get 'cancel'
			post 'delete'
			get 'delete'
		end
	end
	resources :groups do
		resources :albums
		resources :blogs
		resources :articles
		member do
			get 'members'
		end
	end
	resources :honorablebeers
	resources :members do
		member do
			get 'admin'
			post 'admin'
		end
	end
	resources :messages
	resources :miscs
	resources :photos
	resources :abouts
	resources :locations
	resources :reviewbeers do
		resources :comments
		member { post :vote }
	end
	resources :services

	get "users/new"

	root to: 'home#index'

	match '/m_home', to: 'accounts#m_home'	
	match '/signup', to: 'accounts#new'
	match '/copyright', to: 'home#copyright'
	match '/faq', to: 'home#faq'
	match '/learn', to: 'home#learn'
	match '/privacy', to: 'home#privacy'
	match '/support', to: 'home#support'
	match '/terms', to: 'home#terms'
	match '/register', to: 'home#register'
	match '/signin', to: 'sessions#new'
	match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :photo, :city, :country, :description, :exclusive, :visible, :profile_id, :state, :street, :title, :zipcode
	belongs_to :profile
	has_many :member, dependent: :destroy
	has_many :blog
	has_many :article

	has_attached_file :photo, :styles => { :medium => "300x300>", large: "500x500", thumb: "100x100>" }, default_url: "/assets/dasbootresize2.jpg"

	validates :title, presence: true	
	validates :profile_id, presence: true

	default_scope order: 'groups.created_at DESC'

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

	before_filter :signed_in_user
	before_filter :public_private, except: [:index, :new, :create]
	before_filter :correct_group_user,   only: [:edit, :update, :destroy]
	#before_filter :correct_user,   only: [:edit, :update, :destroy]
	#before_filter :admin_user,     only: [:edit, :update]
	respond_to :json, :html, :xml, :js

	def index
		@groups = Group.paginate(page: params[:page])
		#@profile_id= @groups.profile_id
		#@profile= Profile.find(@profile_id)
	end

	def show
		#@profiles= Profile.all
		
		@profiles = Profile.paginate(page: params[:page])
		@group= Group.find(params[:id])
		@invited= @group.member
		@profile_id= @group.profile_id
		@profile= Profile.find(@profile_id)
		@account_id= @profile.account_id
		@account = Account.find(@account_id)
		@member = @group.member.build
		@profile_current = current_profile
		@attendee= Member.find_by_profile_id_and_group_id(@profile_current, @group)
		#blogs & articles
		@blogs = @group.blog.paginate(page: params[:page], per_page: 5)
		@articles = @group.article.paginate(page: params[:page], per_page: 5)
		#members
		@members= Member.where(group_id: @group.id, status: 'attending').limit(5)
		@admin= Member.where(group_id: @group.id, admin: 1).limit(5)
		@declined= Member.where(group_id: @group.id, status: 'not attending').limit(5)
		@not_responded= Member.where(group_id: @group.id, status: 'not responded').limit(5)
		@member_total= Member.where(group_id: @group.id, status: 'attending')
		@admin_total= Member.where(group_id: @group.id, status: 'maybe')
		@declined_total= Member.where(group_id: @group.id, status: 'not attending')
		@not_responded_total= Member.where(group_id: @group.id, status: 'not responded')

	end

	def create
		@profile= current_user.profile
		@group = @profile.group.build(params[:group])
		if @group.save
			flash[:success] = "Group created!"
			redirect_to @group
		else
			render new_group_path
		end
	end

	def edit
		@profile= current_profile
		@group = Group.find(params[:id])
	end

	def destroy
		@profile = current_profile
		@group = Group.find(params[:id])
		if @group.present?
			@group.destroy
			respond_with @group
		end
		#respond_with @group
	end

	def members
		@profiles = Profile.paginate(page: params[:page])
		@group= Group.find(params[:id])
		@profile_id= @group.profile_id
		@profile= Profile.find(@profile_id)
		@invited= @group.member
		@attendee = Member.find_by_profile_id_and_group_id(current_profile, @group)
		@members= Member.where(group_id: @group.id, status: 'attending')
		@admin= Member.where(group_id: @group.id, admin: 1)
		@declined= Member.where(group_id: @group.id, status: 'not attending')
		@not_responded= Member.where(group_id: @group.id, status: 'not responded')
		#@attendees= Profile.where(id: @attending.profile_id)
		@invite = @group.member.build
		
	end

	def new
		@profile = current_profile
		@group = @profile.group.build
		#@group.private = "0"
	end

	def update
		@group= Group.find(params[:id])
		if @group.update_attributes(params[:group])
			flash[:success] = "Beers updated"
			respond_with @group
		else
			render @group
		end
	end

	def invited?(other_user)
		invites.find_by_profile_id(other_user.id)
	end

	def member!(other_user)
		invites.create!(profile_id: other_user.id)
	end

	def uninvite!(other_user)
		invites.find_by_profile_id(other_user.id).destroy
	end


	private

	def correct_user

		#finds group then matches profile_id to Profile then matches matches account_id to Account then asks if its current user 
		@group_id= Group.find(params[:id])
		@profile_id = @group_id.profile_id
		@profile = Profile.find(@profile_id)
		@account_id= @profile.account_id
		@account = Account.find(@account_id)
		redirect_to(@profile) unless current_user?(@account)
	end

	def correct_group_user
		@profile_id = current_profile.id
		@group= Group.find(params[:id])
		@member = Member.find_by_profile_id_and_group_id(current_profile, @group)
		redirect_to(@group) unless (@profile_id == @group.profile_id) || (@member.admin == 1) || @member
	end

	def public_private
		@profile_id = current_profile.id
		@group= Group.find(params[:id])
		@member = Member.find_by_profile_id_and_group_id(current_profile, @group)
		if @group.exclusive == 1 
			flash[:success] = "This Group is Private. You have to be invited to see this group"
			redirect_to(groups_path) unless (@profile_id == @group.profile_id) || @member
		end
		
	end

	def admin_user
		redirect_to(root_path) unless current_user.admin?
	end

end

app/helpers/groups_helper.rb
module GroupsHelper

	def invited(f)
		@invited= Member.find_by_profile_id_and_group_id(f, @group)
		if @invited == nil
			return true
		else
			return false
		end 
	end	

	def group_admin
		if @attendee != nil
			if @attendee.admin == 1
				return true
			else
				return false
			end
		else
			return false
		end
	end

end

app/views/groups/_group.html.erb
<li>
	<%= image_tag group.photo.url(:thumb) %>
	<%= link_to group.title, group %> <br>
	<%= group.profile.s1 %>
	Posted <%= time_ago_in_words(group.created_at) %> ago.
	<% if current_profile?(group.profile) %>
		<%= link_to 'Edit Group',  edit_group_path(group.id) %>
		<%= link_to "delete", group, method: :delete,
							 data: { confirm: "You sure?" },
							 title: group.description %>
	<% end %>

</li>

app/views/groups/_groups.html.erb
<h1><%=@profile.s1 %> Groups</h1>

<% if @profile.group.any? %>
	<h3>Events Started (<%= @profile.group.count %>)</h3>
	<ol class="beers">
		<%= render @groups %>
	</ol>
	<%= will_paginate @groups %>
<% end %>

app/views/groups/edit.html.erb
<%= link_to "Return to Group", @group %>
<%= link_to "Return to Groups Home", groups_path %>

<%= form_for(@group) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">

		<%= f.label :photo, 'Add a photo for group:' %>		
		<%= f.file_field :photo %>

		<%= f.label :title, 'Event Title:' %>	
		<%= f.text_field :title, placeholder: "Event title..." %>


		<%= f.label :exclusive, "Public", :value => "0"  %>
		<%= f.radio_button :exclusive, 0, :checked => true %>
		<%= f.label :exclusive, "Private", :value => "1" %>
		<%= f.radio_button :exclusive, 1 %>

		<%= f.label :visible, "Yes", :value => "0"  %>
		<%= f.radio_button :visible, 0, :checked => true %>
		<%= f.label :visible, "No", :value => "1" %>
		<%= f.radio_button :visible, 1 %>

		<%= f.label :street, 'Street:' %>	
		<%= f.text_field :street %>

		<%= f.label :city, 'City:' %>	
		<%= f.text_field :city%>

		<%= f.label :state, 'State:' %>	
		<%= f.select :state, states%>

		<%= f.label :zipcode, 'Zipcode:' %>	
		<%= f.text_field :zipcode%>

		<%= f.label :description, 'Description:' %>		
		<%= f.text_area :description, placeholder: "Description of group..." %>

	</div>
	<%= f.submit "Post"%>
	<%= link_to "Cancel", @profile %>
<% end %>

app/views/groups/index.html.erb
<%= link_to "Start New Group", new_group_path %>

<h1>Groups</h1>

<%= will_paginate %>

<ul class="list_3_12">
<% @groups.each do |group| %>
	<li>
	<%= image_tag group.photo.url(:thumb) %>
	<%= link_to group.title, group %> <br>
	<%= group.profile.s1 %>
	Posted <%= time_ago_in_words(group.created_at) %> ago.

	</li>
<% end %>
</ul>
<%= will_paginate %>

app/views/groups/members.html.erb
<h1>Invite those Mofos</h1>

<%= @group.title %>
<%= @group.id %>
<%= link_to ('Return to '+@group.title+' group page'), @group %> <br>
<%= render 'members/response' %>
<h3>Members</h3>


<div id="tabs">
	<ul>
		<% if (current_profile.id == @group.profile_id) || group_admin %>
			<li><a href="#Invite">Invite Friends</a></li>
		<% end %>
		<li><a href="#Members">Members</a></li>
		<li><a href="#Admin">Admins</a></li>
		<li><a href="#Decline">Declined</a></li>
		<li><a href="#Noresponse">Not Responded</a></li>
	</ul>
	
	
	<% if (current_profile.id == @group.profile_id) || group_admin %>
		<div id="Invite">
			<h1>Invite Friends</h1>
			<%= render 'members/invite' %>
		</div>
	<% end %>
	
	<div id="Members">
		<h1>Members</h1>
		<p><%= @members.count%> Members</p>
		<%= render 'members/members' %>
	</div>
	<div id="Admin">
		<h2>Admins</h2>
		<p><%= @admin.count%> Admin's</p>
		<%= render 'members/admins' %>


	</div>
	<div id="Decline">
		<h2>Unable to Attend</h2>
		<p><%= @declined.count%> People Unable to Attend</p>
		<%= render 'members/declined' %>

	</div>
	<div id="Noresponse">
		<h2>Has Not Responded</h2>
		<p><%= @not_responded.count%> People Have Not Responded</p>
		<%= render 'members/no_response' %>
	</div>	
</div>

app/views/groups/new.html.erb
<%= link_to "Return to Groups Home", groups_path %>

<%= form_for(@group) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">

		<%= f.label :photo, 'Add a photo for group:' %>		
		<%= f.file_field :photo %>

		<%= f.label :title, 'Event Title:' %>	
		<%= f.text_field :title, placeholder: "Event title..." %>


		<%= f.label :exclusive, "Public", :value => "0"  %>
		<%= f.radio_button :exclusive, 0, :checked => true %>
		<%= f.label :exclusive, "Private", :value => "1" %>
		<%= f.radio_button :exclusive, 1 %>

		<%= f.label :visible, "Yes", :value => "0"  %>
		<%= f.radio_button :visible, 0, :checked => true %>
		<%= f.label :visible, "No", :value => "1" %>
		<%= f.radio_button :visible, 1 %>

		<%= f.label :street, 'Street:' %>	
		<%= f.text_field :street %>

		<%= f.label :city, 'City:' %>	
		<%= f.text_field :city%>

		<%= f.label :state, 'State:' %>	
		<%= f.select :state, states%>

		<%= f.label :zipcode, 'Zipcode:' %>	
		<%= f.text_field :zipcode%>

		<%= f.label :description, 'Description:' %>		
		<%= f.text_area :description, placeholder: "Description of group..." %>

	</div>
	<%= f.submit "Post"%>
	<%= link_to "Cancel", @profile %>
<% end %>

app/views/groups/show.html.erb
<%= link_to "Return to Groups Home", groups_path %>

<%= image_tag @group.photo.url(:thumb) %>
<%= @group.title %>
<%= @group.description %>
<% if current_profile?(@group.profile) || group_admin %>
		<%= link_to 'Edit Group',  edit_group_path(@group.id) %>
		<% if current_profile?(@group.profile) %>
			<%= link_to "delete", @group, method: :delete,
						             data: { confirm: "You sure?" },
						             title: @group.description %>
		<% end %>
	<% end %>

<%= link_to "Invite Friends", members_group_path %>

<%= render 'members/response' %>

<%= link_to 'Start Blog from this Group',  new_group_blog_path(@group) %>
<h3>Blogs Started (<%= @group.blog.count %>)</h3>
<%= render 'blogs/blogs' %>

<%= link_to 'Start News Article from this Group',  new_group_article_path(@group) %>
<h3>News Artciles Started (<%= @group.article.count %>)</h3>
<%= render 'articles/articles' %>

<div id="tabs">
	<ul>
		<li><a href="#Members">Members</a></li>
		<li><a href="#Admin">Admins</a></li>
		<li><a href="#Decline">Declined</a></li>
		<li><a href="#Noresponse">Not Responded</a></li>
	</ul>
	
	<div id="Members">
		<h1>Members</h1>
		<p><%= @member_total.count%> Members</p>
		<%= render 'members/members' %>
	</div>
	<div id="Admin">
		<h2>Admins</h2>
		<p><%= @admin_total.count%> Admin's</p>
		<%= render 'members/admins' %>


	</div>
	<div id="Decline">
		<h2>Unable to Attend</h2>
		<p><%= @declined_total.count%> People Unable to Attend</p>
		<%= render 'members/declined' %>

	</div>
	<div id="Noresponse">
		<h2>Has Not Responded</h2>
		<p><%= @not_responded_total.count%> People Have Not Responded</p>
		<%= render 'members/no_response' %>
	</div>	
</div>