config/routes.rb
KaljaaFb::Application.routes.draw do
	resources :accounts do
		member do
			get :following, :followers
		end
	end
	resources :sessions, only: [:new, :create, :destroy]
	resources :microposts, only: [:create, :destroy]
	resources :relationships, only: [:create, :destroy]
	resources :profiles do
		resources :albums
		member do
			get :info
		end
	end
	resources :activities
	resources :albums do
		resources :photos
	end
	resources :articles do
		resources :albums
	end
	resources :beers do
		resources :comments
		member { post :vote }
	end
	resources :beercentrals
	resources :blogs do
		resources :albums
	end
	resources :conversations, only: [:index, :show, :new, :create] do
		member do
			post :reply
			post :trash
			post :untrash
		end
	end
	resources :interests
	resources :invites do
		member do
			get 'admin'
			post 'admin'
		end
	end
	resources :events do
		resources :albums
		resources :blogs
		resources :articles
		member do
			get 'invite'
		end
	end
	resources :favbreweries
	resources :favbeers
	resources :friendships do
		member do
			post 'accept'
			get 'accept'
			post 'decline'
			get 'decline'
			post 'cancel'
			get 'cancel'
			post 'delete'
			get 'delete'
		end
	end
	resources :groups do
		resources :albums
		resources :blogs
		resources :articles
		member do
			get 'members'
		end
	end
	resources :honorablebeers
	resources :members do
		member do
			get 'admin'
			post 'admin'
		end
	end
	resources :messages
	resources :miscs
	resources :photos
	resources :abouts
	resources :locations
	resources :reviewbeers do
		resources :comments
		member { post :vote }
	end
	resources :services

	get "users/new"

	root to: 'home#index'

	match '/m_home', to: 'accounts#m_home'	
	match '/signup', to: 'accounts#new'
	match '/copyright', to: 'home#copyright'
	match '/faq', to: 'home#faq'
	match '/learn', to: 'home#learn'
	match '/privacy', to: 'home#privacy'
	match '/support', to: 'home#support'
	match '/terms', to: 'home#terms'
	match '/register', to: 'home#register'
	match '/signin', to: 'sessions#new'
	match '/signout', to: 'sessions#destroy', via: :delete

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<span class="user">
		<%= link_to feed_item.account.email, feed_item.account %>
	</span>
	<span class="content"><%= feed_item.content %></span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
	</span>
	<% if current_user?(feed_item.account) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post"%>
<% end %>

app/views/shared/_stats.html.erb
<% @account ||= current_user %>
<div class="stats">
  <a href="<%= following_account_path(@account) %>">
    <strong id="following" class="stat">
      <%= @account.followed_accounts.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_account_path(@account) %>">
    <strong id="followers" class="stat">
      <%= @account.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<h1>
  <%= current_user.email %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>